---
title: "StorySurvey"
image: "abcd.svg"
links:
  - label: More info
    url: "https://drive.google.com/file/d/1ipxfjPy6ftH6IrhtiOohvMx6pAcDMhZt/view?usp=sharing"
  - label: Causal Map
    url: "http://causalmap.app"
  - label: Email
    url: "mailto:hello@causalmap.app"
output:
  postcards::trestles
---

# 🦉StorySurvey

**StorySurvey** is like SurveyMonkey for stories. You design a survey, and people fill it in online.

In your survey you ask people questions which prompt them to make connections and give reasons, e.g.

- What were the key factors which led to Russia’s attack on Ukraine?
- What do you think makes for safer streets?

The StorySurvey algorithm then asks *the reason behind each reason*. 

Then the app combines the information from different respondents into an overview map. 
Survey administrators can get a visual overview of respondents’ explanations: where they agree, and where they disagree.

Small surveys are free! StorySurvey is online-only, so respondents need an internet connection.

StorySurvey will be publicly available very soon. [Write to us](mailto:hello@causalmap.app) if you are interested or want to know more, or [join the waiting list](https://forms.wix.com/f/6992844431304950386).

----

🦉 StorySurvey is provided by [Causal Map Ltd](http://causalmap.app).
